#!/bin/sh
# V6 d2-law droplet, axisymmetric wedge. Usage: ./Allrun <R0/h> [nProcs] [tEnd]
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
n=${1:-16}
tend=${3:-2e-3}
np=${2:-4}
python3 gen.py "$n" mesh "$tend" > log.gen || exit 1
restore0Dir
runApplication blockMesh
runApplication -s C0 postProcess -func writeCellCentres -time 0
runApplication -s V0 postProcess -func writeCellVolumes -time 0
mv 0/V constant/V
python3 gen.py "$n" init >> log.gen || exit 1
rm -f 0/C 0/Cx 0/Cy 0/Cz
if [ "$np" -gt 1 ]
then
    sed -i "s/numberOfSubdomains.*/numberOfSubdomains $np;/" system/decomposeParDict
    runApplication decomposePar
    runParallel $(getApplication)
    runApplication reconstructPar -latestTime
else
    runApplication $(getApplication)
fi
python3 post.py > log.post 2>&1
