#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# V2: 1D Stefan melting (one-phase Neumann problem), equal densities.
# Setup inherited unchanged from run/sheikh-1d-stefan (Shaikh et al. 2016
# benchmark, paraffin: rho 750, cp 2400, k 0.21, L 175000, Tm 313, Tw 350);
# only the alpha solver dictionary was adapted for isoAdvector.

restore0Dir
runApplication blockMesh
runApplication -s C0 postProcess -func writeCellCentres -time 0
runApplication -s init python3 init_fields.py   # row-uniform alpha and T
rm -f 0/C 0/Cx 0/Cy 0/Cz
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar -newTimes
python3 post.py > log.post 2>&1
#------------------------------------------------------------------------------
