#!/bin/sh
# Usage: ./Allrun <planar|wedge> <R/h> [nSteps]
# Extra curvature/CSF settings go in constant/curvatureSettings (optional).
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
python3 gen.py "$1" "$2" "$3" || exit 1
restore0Dir
runApplication blockMesh
runApplication -s C0 postProcess -func writeCellCentres -time 0
runApplication -s alpha python3 init_alpha.py
runApplication $(getApplication)
runApplication -s C postProcess -func writeCellCentres -latestTime
runApplication -s V postProcess -func writeCellVolumes -latestTime
python3 post.py > log.post 2>&1
